apiVersion: cert-manager.io/v1
 
kind: Certificate
metadata:
  name: calcas0731-com-tls
spec:
  secretName: calcas0731-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: calcas0731.com
  dnsNames:
    - calcas0731.com
    - www.calcas0731.com